---
- hosts: wp1
  tasks:
   - name: aaaa
     lineinfile:
        path: /var/www/proofSyntax/proof1.cfg
        line: '192.168.1.99 foo.lab.net foo'
     sudo: yes
   - name: bbb
     lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=enforcing'
     sudo:yes
